name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Qt
      run: |
        sudo apt-get update
        sudo apt-get install qt5-base
        export PATH=$PATH:/usr/lib/x86_64-linux-gnu/qt5
        echo 'export PATH="$PATH:/usr/lib/x86_64-linux-gnu/qt5"' >> $GITHUB_ENV

    - name: Install Emscripten
      run: |
        git clone https://github.com/emscripten-core/emsdk.git
        cd emsdk
        ./emsdk install latest
        ./emsdk activate latest

    - name: Set environment variables
      run: |
        source emsdk/emsdk_env.sh

    - name: Build project
      run: |
        qmake FoodTracker/FoodTracker.pro -spec emscripten
        make

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: ./path/to/output/directory
