name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: gh-pages
    - name: create docs directory
      run: mkdir docs
    - name: Copy files to gh-pages branch
      run: |
        cp -r Builds/* docs/
        mv docs/FoodTracker.html docs/index.html

    - name: Commit and push changes
      run: |
        git config --local user.email "github-actions@github.com"
        git config --local user.name "GitHub Actions"
        git add -A
        git commit -m "Update GitHub Pages"
        git push -f origin gh-pages
