name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Emscripten SDK
      uses: trzeci/emscripten-action@v1

    - name: Set environment variables
      run: |
        echo "EMSDK: $EMSDK"
        source $EMSDK/emsdk_env.sh
        echo "EMSCRIPTEN: $EMSCRIPTEN"

    - name: Build project
      run: |
        # Configure the project with qmake
        qmake FoodTracker/FoodTracker.pro -spec wasm-emscripten
        # Build the project
        make

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: ./path/to/output/directory
